# Generated by Django 2.2.6 on 2019-10-13 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History_db',
            fields=[
                ('history_num', models.AutoField(primary_key=True, serialize=False)),
                ('user_num', models.IntegerField()),
                ('history_image_name', models.CharField(max_length=45)),
                ('history_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('style_name', models.CharField(max_length=45)),
                ('history_location', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Member_db',
            fields=[
                ('user_num', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('join_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('profile', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Reply_db',
            fields=[
                ('reply_num', models.AutoField(primary_key=True, serialize=False)),
                ('time_num', models.IntegerField()),
                ('user_num', models.IntegerField()),
                ('reply_comment', models.CharField(max_length=45)),
                ('reply_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Style_db',
            fields=[
                ('style_num', models.AutoField(primary_key=True, serialize=False)),
                ('style_name', models.CharField(max_length=45)),
                ('style_path', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline_db',
            fields=[
                ('time_num', models.AutoField(primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('time_image_name', models.CharField(max_length=45)),
                ('time_comment', models.CharField(max_length=45)),
                ('time_location', models.CharField(max_length=45)),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illusion.Member_db')),
            ],
        ),
    ]
