# Generated by Django 2.2.6 on 2019-10-13 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_db',
            name='history_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='member_db',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='member_db',
            name='profile',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='reply_db',
            name='reply_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='timeline_db',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
