# Generated by Django 2.2.6 on 2019-10-17 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('illusion', '0003_auto_20191015_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_db',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illusion.Member_db'),
        ),
        migrations.AlterField(
            model_name='member_db',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reply_db',
            name='time_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illusion.Timeline_db'),
        ),
        migrations.AlterField(
            model_name='reply_db',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illusion.Member_db'),
        ),
    ]
