# Generated by Django 2.2.6 on 2019-10-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illusion', '0004_auto_20191017_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_db',
            name='history_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='member_db',
            name='join_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='reply_db',
            name='reply_time',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='timeline_db',
            name='upload_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
