# Generated by Django 2.2.6 on 2019-10-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illusion', '0006_auto_20191021_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_db',
            name='password',
            field=models.CharField(default=1234, max_length=45),
            preserve_default=False,
        ),
    ]
