# Generated by Django 2.2.6 on 2019-10-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illusion', '0009_auto_20191028_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentImage',
        ),
    ]
