# Generated by Django 2.2.6 on 2019-10-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illusion', '0011_filetest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileTest',
            new_name='ContentImage',
        ),
    ]
