# Generated by Django 2.2.6 on 2019-10-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illusion', '0012_auto_20191028_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='유저 UID (Firebase 에서 자동 생성)')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='최근 로그인 일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'db_table': 'users',
            },
        ),
    ]
