# Generated by Django 2.2.6 on 2019-10-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illusion', '0013_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
