# Generated by Django 2.2.6 on 2019-11-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illusion', '0016_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='style_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='preview',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
