# Generated by Django 2.2.6 on 2019-11-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illusion', '0017_auto_20191102_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preview',
        ),
    ]
